import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:go_router/go_router.dart';
import 'package:image_picker/image_picker.dart';
import 'package:file_picker/file_picker.dart';
import 'package:lexi_quest/core/config/supabase_config.dart';
import 'package:lexi_quest/core/theme/app_colors.dart';
import 'package:lexi_quest/core/theme/app_fonts.dart';
import 'package:lexi_quest/features/annotation/data/models/annotation_model.dart';
import 'package:lexi_quest/features/annotation/bloc/annotation_bloc.dart';
import 'package:lexi_quest/features/annotation/bloc/annotation_event.dart';
import 'package:lexi_quest/features/annotation/bloc/annotation_state.dart';

/// Screen for creating new annotations that can be added to projects
class CreateAnnotationScreen extends StatefulWidget {
  final AnnotationType type;
  final String? projectId;
  final int? projectXp;

  const CreateAnnotationScreen({
    super.key,
    required this.type,
    this.projectId,
    this.projectXp,
  });

  @override
  State<CreateAnnotationScreen> createState() => _CreateAnnotationScreenState();
}

class _CreateAnnotationScreenState extends State<CreateAnnotationScreen> {
  final _formKey = GlobalKey<FormState>();
  final _contentController = TextEditingController();
  final _instructionsController = TextEditingController();
  final _labelController = TextEditingController();
  final List<String> _labels = [];
  late int _xpReward;
  String? _uploadedFileUrl;
  bool _isUploading = false;

  @override
  void initState() {
    super.initState();
    // Use project XP if provided, otherwise default to 10
    _xpReward = widget.projectXp ?? 10;
  }

  @override
  void dispose() {
    _contentController.dispose();
    _instructionsController.dispose();
    _labelController.dispose();
    super.dispose();
  }

  void _addLabel() {
    final label = _labelController.text.trim();
    if (label.isNotEmpty && !_labels.contains(label)) {
      setState(() {
        _labels.add(label);
        _labelController.clear();
      });
    }
  }

  void _removeLabel(String label) {
    setState(() {
      _labels.remove(label);
    });
  }

  Future<void> _pickImage() async {
    final ImagePicker picker = ImagePicker();
    final XFile? image = await picker.pickImage(
      source: ImageSource.gallery,
      maxWidth: 1920,
      maxHeight: 1920,
      imageQuality: 85,
    );

    if (image != null) {
      setState(() => _isUploading = true);

      if (!mounted) return;
      
      try {
        context.read<AnnotationBloc>().add(UploadAnnotationImage(filePath: image.path));
      } catch (e) {
        if (mounted) {
          ScaffoldMessenger.of(context).showSnackBar(
            SnackBar(
              content: Text('Failed to upload image: $e'),
              backgroundColor: AppColors.error,
            ),
          );
        }
        if (mounted) {
          setState(() => _isUploading = false);
        }
      }
    }
  }

  Future<void> _pickAudio() async {
    final result = await FilePicker.platform.pickFiles(
      type: FileType.audio,
    );

    if (result != null && result.files.single.path != null) {
      setState(() => _isUploading = true);

      if (!mounted) return;
      
      try {
        context.read<AnnotationBloc>().add(
          UploadAnnotationAudio(filePath: result.files.single.path!),
        );
      } catch (e) {
        if (mounted) {
          ScaffoldMessenger.of(context).showSnackBar(
            SnackBar(
              content: Text('Failed to upload audio: $e'),
              backgroundColor: AppColors.error,
            ),
          );
        }
        if (mounted) {
          setState(() => _isUploading = false);
        }
      }
    }
  }

  void _createAnnotation() {
    if (!_formKey.currentState!.validate()) return;

    if (_labels.isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(
          content: Text('Please add at least one label'),
          backgroundColor: AppColors.error,
        ),
      );
      return;
    }

    // Ensure user is logged in
    final userId = SupabaseConfig.currentUserId;
    if (userId == null) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(
          content: Text('You must be logged in to create annotations'),
          backgroundColor: AppColors.error,
        ),
      );
      return;
    }

    // For image/audio, check if file is uploaded
    if (widget.type == AnnotationType.image || widget.type == AnnotationType.audio) {
      if (_uploadedFileUrl == null) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('Please upload ${widget.type == AnnotationType.image ? 'an image' : 'an audio file'}'),
            backgroundColor: AppColors.error,
          ),
        );
        return;
      }
    }

    final annotation = AnnotationModel(
      id: '', // Will be generated by database
      type: widget.type,
      content: widget.type == AnnotationType.text 
          ? _contentController.text.trim() 
          : '', // Empty content for image/audio
      instructions: _instructionsController.text.trim().isEmpty
          ? null
          : _instructionsController.text.trim(),
      imageUrl: widget.type == AnnotationType.image ? _uploadedFileUrl : null,
      audioUrl: widget.type == AnnotationType.audio ? _uploadedFileUrl : null,
      labels: _labels,
      createdAt: DateTime.now(),
      xpReward: _xpReward,
      createdBy: userId, // Set to current user
    );

    context.read<AnnotationBloc>().add(CreateAnnotation(annotation: annotation));
  }

  Color _getTypeColor() {
    switch (widget.type) {
      case AnnotationType.text:
        return AppColors.primaryIndigo600;
      case AnnotationType.image:
        return AppColors.secondaryGreen500;
      case AnnotationType.audio:
        return AppColors.secondaryAmber500;
    }
  }

  IconData _getTypeIcon() {
    switch (widget.type) {
      case AnnotationType.text:
        return Icons.text_fields;
      case AnnotationType.image:
        return Icons.image;
      case AnnotationType.audio:
        return Icons.audiotrack;
    }
  }

  String _getTypeLabel() {
    switch (widget.type) {
      case AnnotationType.text:
        return 'Text';
      case AnnotationType.image:
        return 'Image';
      case AnnotationType.audio:
        return 'Audio';
    }
  }

  String _getContentHint() {
    switch (widget.type) {
      case AnnotationType.text:
        return 'Enter the text to be annotated';
      case AnnotationType.image:
        return 'Enter image URL or description';
      case AnnotationType.audio:
        return 'Enter audio URL or description';
    }
  }

  @override
  Widget build(BuildContext context) {
    return BlocConsumer<AnnotationBloc, AnnotationState>(
      listener: (context, state) {
        if (state is AnnotationCreated) {
          ScaffoldMessenger.of(context).showSnackBar(
            const SnackBar(
              content: Text('Annotation created successfully!'),
              backgroundColor: AppColors.secondaryGreen500,
            ),
          );
          context.pop(state.annotation);
        } else if (state is AnnotationError) {
          ScaffoldMessenger.of(context).showSnackBar(
            SnackBar(
              content: Text(state.message),
              backgroundColor: AppColors.error,
            ),
          );
        } else if (state is FileUploaded) {
          setState(() {
            _uploadedFileUrl = state.url;
            _isUploading = false;
          });
          ScaffoldMessenger.of(context).showSnackBar(
            SnackBar(
              content: Text('${widget.type == AnnotationType.image ? 'Image' : 'Audio'} uploaded successfully!'),
              backgroundColor: AppColors.secondaryGreen500,
            ),
          );
        }
      },
      builder: (context, state) {
        final isLoading = state is AnnotationLoading;

        return Scaffold(
          backgroundColor: AppColors.surface,
          body: SafeArea(
            child: Column(
              children: [
                // Modern Gradient Header
                Container(
                  width: double.infinity,
                  padding: const EdgeInsets.all(20),
                  decoration: BoxDecoration(
                    gradient: LinearGradient(
                      colors: [_getTypeColor(), _getTypeColor().withValues(alpha: 0.8)],
                      begin: Alignment.topLeft,
                      end: Alignment.bottomRight,
                    ),
                    borderRadius: const BorderRadius.only(
                      bottomLeft: Radius.circular(24),
                      bottomRight: Radius.circular(24),
                    ),
                  ),
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Row(
                        children: [
                          IconButton(
                            onPressed: () => context.pop(),
                            icon: const Icon(
                              Icons.arrow_back,
                              color: AppColors.onPrimary,
                            ),
                          ),
                          const SizedBox(width: 8),
                          Icon(
                            _getTypeIcon(),
                            color: AppColors.onPrimary,
                            size: 28,
                          ),
                          const SizedBox(width: 12),
                          Expanded(
                            child: Text(
                              'Create ${_getTypeLabel()} Annotation',
                              style: AppFonts.headlineMedium.copyWith(
                                color: AppColors.onPrimary,
                                fontWeight: FontWeight.bold,
                              ),
                            ),
                          ),
                        ],
                      ),
                      const SizedBox(height: 8),
                      Text(
                        'Create a new annotation task for your project',
                        style: AppFonts.bodyMedium.copyWith(
                          color: AppColors.onPrimary.withValues(alpha: 0.9),
                        ),
                      ),
                    ],
                  ),
                ),

                // Form Content
                Expanded(
                  child: SingleChildScrollView(
                    padding: const EdgeInsets.all(20),
                    child: Form(
                      key: _formKey,
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          // Content Field
                          Text(
                            'Content',
                            style: AppFonts.titleMedium.copyWith(
                              fontWeight: FontWeight.bold,
                              color: AppColors.onBackground,
                            ),
                          ),
                          const SizedBox(height: 8),
                          
                          // Show file upload for image/audio, text field for text
                          if (widget.type == AnnotationType.image || widget.type == AnnotationType.audio) ...[
                            Container(
                              width: double.infinity,
                              padding: const EdgeInsets.all(20),
                              decoration: BoxDecoration(
                                color: AppColors.background,
                                borderRadius: BorderRadius.circular(12),
                                border: Border.all(
                                  color: _uploadedFileUrl != null 
                                      ? AppColors.secondaryGreen500 
                                      : AppColors.neutralSlate600_30,
                                  width: _uploadedFileUrl != null ? 2 : 1,
                                ),
                              ),
                              child: Column(
                                children: [
                                  Icon(
                                    _uploadedFileUrl != null 
                                        ? Icons.check_circle 
                                        : _getTypeIcon(),
                                    size: 48,
                                    color: _uploadedFileUrl != null 
                                        ? AppColors.secondaryGreen500 
                                        : _getTypeColor(),
                                  ),
                                  const SizedBox(height: 12),
                                  Text(
                                    _uploadedFileUrl != null 
                                        ? '${widget.type == AnnotationType.image ? 'Image' : 'Audio'} uploaded successfully!' 
                                        : 'Tap to upload ${widget.type == AnnotationType.image ? 'an image' : 'an audio file'}',
                                    style: AppFonts.bodyMedium.copyWith(
                                      color: _uploadedFileUrl != null 
                                          ? AppColors.secondaryGreen500 
                                          : AppColors.onSurfaceVariant,
                                      fontWeight: _uploadedFileUrl != null ? FontWeight.bold : FontWeight.normal,
                                    ),
                                    textAlign: TextAlign.center,
                                  ),
                                  if (_isUploading) ...[
                                    const SizedBox(height: 16),
                                    const CircularProgressIndicator(),
                                  ] else if (_uploadedFileUrl == null) ...[
                                    const SizedBox(height: 16),
                                    ElevatedButton.icon(
                                      onPressed: widget.type == AnnotationType.image 
                                          ? _pickImage 
                                          : _pickAudio,
                                      icon: const Icon(Icons.upload_file),
                                      label: Text('Choose ${widget.type == AnnotationType.image ? 'Image' : 'Audio'}'),
                                      style: ElevatedButton.styleFrom(
                                        backgroundColor: _getTypeColor(),
                                      ),
                                    ),
                                  ],
                                ],
                              ),
                            ),
                          ] else ...[
                            TextFormField(
                              controller: _contentController,
                              maxLines: 6,
                              style: AppFonts.bodyMedium.copyWith(
                                color: AppColors.onBackground,
                              ),
                              decoration: InputDecoration(
                                hintText: _getContentHint(),
                                hintStyle: AppFonts.bodyMedium.copyWith(
                                  color: AppColors.onSurfaceVariant,
                                ),
                                filled: true,
                                fillColor: AppColors.background,
                                prefixIcon: Padding(
                                  padding: const EdgeInsets.only(bottom: 60),
                                  child: Icon(
                                    _getTypeIcon(),
                                    color: _getTypeColor(),
                                  ),
                                ),
                                border: OutlineInputBorder(
                                  borderRadius: BorderRadius.circular(12),
                                  borderSide: BorderSide.none,
                                ),
                                enabledBorder: OutlineInputBorder(
                                  borderRadius: BorderRadius.circular(12),
                                  borderSide: BorderSide(
                                    color: AppColors.neutralSlate600_30,
                                  ),
                                ),
                                focusedBorder: OutlineInputBorder(
                                  borderRadius: BorderRadius.circular(12),
                                  borderSide: BorderSide(
                                    color: _getTypeColor(),
                                    width: 2,
                                  ),
                                ),
                              ),
                              validator: (value) {
                                if (value == null || value.isEmpty) {
                                  return 'Please enter content';
                                }
                                return null;
                              },
                            ),
                          ],
                          const SizedBox(height: 24),

                          // Instructions Field
                          Text(
                            'Instructions (Optional)',
                            style: AppFonts.titleMedium.copyWith(
                              fontWeight: FontWeight.bold,
                              color: AppColors.onBackground,
                            ),
                          ),
                          const SizedBox(height: 8),
                          TextFormField(
                            controller: _instructionsController,
                            maxLines: 3,
                            style: AppFonts.bodyMedium.copyWith(
                              color: AppColors.onBackground,
                            ),
                            decoration: InputDecoration(
                              hintText: 'Provide instructions for annotators...',
                              hintStyle: AppFonts.bodyMedium.copyWith(
                                color: AppColors.onSurfaceVariant,
                              ),
                              filled: true,
                              fillColor: AppColors.background,
                              prefixIcon: const Padding(
                                padding: EdgeInsets.only(bottom: 40),
                                child: Icon(
                                  Icons.info_outline,
                                  color: AppColors.primaryIndigo600,
                                ),
                              ),
                              border: OutlineInputBorder(
                                borderRadius: BorderRadius.circular(12),
                                borderSide: BorderSide.none,
                              ),
                              enabledBorder: OutlineInputBorder(
                                borderRadius: BorderRadius.circular(12),
                                borderSide: BorderSide(
                                  color: AppColors.neutralSlate600_30,
                                ),
                              ),
                              focusedBorder: OutlineInputBorder(
                                borderRadius: BorderRadius.circular(12),
                                borderSide: const BorderSide(
                                  color: AppColors.primaryIndigo600,
                                  width: 2,
                                ),
                              ),
                            ),
                          ),
                          const SizedBox(height: 24),

                          // Labels
                          Text(
                            'Labels',
                            style: AppFonts.titleMedium.copyWith(
                              fontWeight: FontWeight.bold,
                              color: AppColors.onBackground,
                            ),
                          ),
                          const SizedBox(height: 4),
                          Text(
                            'Add labels that annotators can choose from',
                            style: AppFonts.bodySmall.copyWith(
                              color: AppColors.onSurfaceVariant,
                            ),
                          ),
                          const SizedBox(height: 8),
                          Row(
                            children: [
                              Expanded(
                                child: TextField(
                                  controller: _labelController,
                                  style: AppFonts.bodyMedium.copyWith(
                                    color: AppColors.onBackground,
                                  ),
                                  decoration: InputDecoration(
                                    hintText: 'Add label (e.g., Positive, Negative)',
                                    hintStyle: AppFonts.bodyMedium.copyWith(
                                      color: AppColors.onSurfaceVariant,
                                    ),
                                    filled: true,
                                    fillColor: AppColors.background,
                                    prefixIcon: Icon(
                                      Icons.label,
                                      color: _getTypeColor(),
                                    ),
                                    border: OutlineInputBorder(
                                      borderRadius: BorderRadius.circular(12),
                                      borderSide: BorderSide.none,
                                    ),
                                    enabledBorder: OutlineInputBorder(
                                      borderRadius: BorderRadius.circular(12),
                                      borderSide: BorderSide(
                                        color: AppColors.neutralSlate600_30,
                                      ),
                                    ),
                                    focusedBorder: OutlineInputBorder(
                                      borderRadius: BorderRadius.circular(12),
                                      borderSide: BorderSide(
                                        color: _getTypeColor(),
                                        width: 2,
                                      ),
                                    ),
                                  ),
                                  onSubmitted: (_) => _addLabel(),
                                ),
                              ),
                              const SizedBox(width: 8),
                              Container(
                                decoration: BoxDecoration(
                                  color: _getTypeColor(),
                                  borderRadius: BorderRadius.circular(12),
                                ),
                                child: IconButton(
                                  onPressed: _addLabel,
                                  icon: const Icon(Icons.add),
                                  color: AppColors.onPrimary,
                                ),
                              ),
                            ],
                          ),
                          if (_labels.isNotEmpty) ...[
                            const SizedBox(height: 16),
                            Wrap(
                              spacing: 8,
                              runSpacing: 8,
                              children: _labels.map((label) {
                                return Chip(
                                  label: Text(
                                    label,
                                    style: AppFonts.bodySmall.copyWith(
                                      color: _getTypeColor(),
                                    ),
                                  ),
                                  backgroundColor: _getTypeColor().withValues(alpha: 0.1),
                                  deleteIconColor: _getTypeColor(),
                                  onDeleted: () => _removeLabel(label),
                                  deleteIcon: const Icon(Icons.close, size: 18),
                                  side: BorderSide(
                                    color: _getTypeColor().withValues(alpha: 0.3),
                                  ),
                                );
                              }).toList(),
                            ),
                          ],
                          const SizedBox(height: 24),

                          // XP Reward
                          Text(
                            'XP Reward',
                            style: AppFonts.titleMedium.copyWith(
                              fontWeight: FontWeight.bold,
                              color: AppColors.onBackground,
                            ),
                          ),
                          const SizedBox(height: 8),
                          Container(
                            padding: const EdgeInsets.all(16),
                            decoration: BoxDecoration(
                              color: AppColors.background,
                              borderRadius: BorderRadius.circular(12),
                              border: Border.all(
                                color: AppColors.neutralSlate600_30,
                              ),
                            ),
                            child: Column(
                              children: [
                                Row(
                                  mainAxisAlignment: MainAxisAlignment.spaceBetween,
                                  children: [
                                    Text(
                                      'XP Value',
                                      style: AppFonts.bodyMedium.copyWith(
                                        color: AppColors.onSurfaceVariant,
                                      ),
                                    ),
                                    Container(
                                      padding: const EdgeInsets.symmetric(
                                        horizontal: 12,
                                        vertical: 6,
                                      ),
                                      decoration: BoxDecoration(
                                        color: AppColors.secondaryAmber500.withValues(alpha: 0.1),
                                        borderRadius: BorderRadius.circular(8),
                                      ),
                                      child: Row(
                                        children: [
                                          const Icon(
                                            Icons.star,
                                            size: 16,
                                            color: AppColors.secondaryAmber500,
                                          ),
                                          const SizedBox(width: 4),
                                          Text(
                                            '$_xpReward XP',
                                            style: AppFonts.titleSmall.copyWith(
                                              color: AppColors.secondaryAmber500,
                                              fontWeight: FontWeight.bold,
                                            ),
                                          ),
                                        ],
                                      ),
                                    ),
                                  ],
                                ),
                                if (widget.projectXp != null) ...[
                                  const SizedBox(height: 8),
                                  Text(
                                    'XP is set by the project',
                                    style: AppFonts.bodySmall.copyWith(
                                      color: AppColors.onSurfaceVariant,
                                      fontStyle: FontStyle.italic,
                                    ),
                                  ),
                                ] else
                                  Slider(
                                    value: _xpReward.toDouble(),
                                    min: 5,
                                    max: 50,
                                    divisions: 9,
                                    label: '$_xpReward XP',
                                    activeColor: _getTypeColor(),
                                    onChanged: (value) {
                                      setState(() {
                                        _xpReward = value.toInt();
                                      });
                                    },
                                  ),
                              ],
                            ),
                          ),
                          const SizedBox(height: 32),

                          // Create Button
                          SizedBox(
                            width: double.infinity,
                            child: ElevatedButton(
                              onPressed: isLoading ? null : _createAnnotation,
                              style: ElevatedButton.styleFrom(
                                backgroundColor: _getTypeColor(),
                                padding: const EdgeInsets.symmetric(vertical: 16),
                                shape: RoundedRectangleBorder(
                                  borderRadius: BorderRadius.circular(12),
                                ),
                                elevation: 2,
                              ),
                              child: isLoading
                                  ? const SizedBox(
                                      height: 20,
                                      width: 20,
                                      child: CircularProgressIndicator(
                                        color: AppColors.onPrimary,
                                        strokeWidth: 2,
                                      ),
                                    )
                                  : Row(
                                      mainAxisAlignment: MainAxisAlignment.center,
                                      children: [
                                        const Icon(
                                          Icons.check_circle,
                                          color: AppColors.onPrimary,
                                        ),
                                        const SizedBox(width: 8),
                                        Text(
                                          'Create Annotation',
                                          style: AppFonts.buttonText.copyWith(
                                            color: AppColors.onPrimary,
                                            fontWeight: FontWeight.bold,
                                          ),
                                        ),
                                      ],
                                    ),
                            ),
                          ),
                          const SizedBox(height: 20),
                        ],
                      ),
                    ),
                  ),
                ),
              ],
            ),
          ),
        );
      },
    );
  }
}
