import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:go_router/go_router.dart';
import 'package:lexi_quest/core/config/supabase_config.dart';
import 'package:lexi_quest/core/theme/app_colors.dart';
import 'package:lexi_quest/core/theme/app_fonts.dart';
import 'package:lexi_quest/features/annotation/data/models/annotation_model.dart';
import 'package:lexi_quest/features/annotation/bloc/annotation_bloc.dart';
import 'package:lexi_quest/features/annotation/bloc/annotation_event.dart';
import 'package:lexi_quest/features/annotation/bloc/annotation_state.dart';

/// Screen for creating new annotations that can be added to projects
class CreateAnnotationScreen extends StatefulWidget {
  final AnnotationType type;
  final String? projectId;

  const CreateAnnotationScreen({
    super.key,
    required this.type,
    this.projectId,
  });

  @override
  State<CreateAnnotationScreen> createState() => _CreateAnnotationScreenState();
}

class _CreateAnnotationScreenState extends State<CreateAnnotationScreen> {
  final _formKey = GlobalKey<FormState>();
  final _contentController = TextEditingController();
  final _instructionsController = TextEditingController();
  final _labelController = TextEditingController();
  final List<String> _labels = [];
  int _xpReward = 10;

  @override
  void dispose() {
    _contentController.dispose();
    _instructionsController.dispose();
    _labelController.dispose();
    super.dispose();
  }

  void _addLabel() {
    final label = _labelController.text.trim();
    if (label.isNotEmpty && !_labels.contains(label)) {
      setState(() {
        _labels.add(label);
        _labelController.clear();
      });
    }
  }

  void _removeLabel(String label) {
    setState(() {
      _labels.remove(label);
    });
  }

  void _createAnnotation() {
    if (!_formKey.currentState!.validate()) return;

    if (_labels.isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(
          content: Text('Please add at least one label'),
          backgroundColor: AppColors.error,
        ),
      );
      return;
    }

    final annotation = AnnotationModel(
      id: '', // Will be generated by database
      type: widget.type,
      content: _contentController.text.trim(),
      instructions: _instructionsController.text.trim().isEmpty
          ? null
          : _instructionsController.text.trim(),
      labels: _labels,
      createdAt: DateTime.now(),
      xpReward: _xpReward,
      createdBy: SupabaseConfig.currentUserId, // Set to current user
    );

    context.read<AnnotationBloc>().add(CreateAnnotation(annotation: annotation));
  }

  Color _getTypeColor() {
    switch (widget.type) {
      case AnnotationType.text:
        return AppColors.primaryIndigo600;
      case AnnotationType.image:
        return AppColors.secondaryGreen500;
      case AnnotationType.audio:
        return AppColors.secondaryAmber500;
    }
  }

  IconData _getTypeIcon() {
    switch (widget.type) {
      case AnnotationType.text:
        return Icons.text_fields;
      case AnnotationType.image:
        return Icons.image;
      case AnnotationType.audio:
        return Icons.audiotrack;
    }
  }

  String _getTypeLabel() {
    switch (widget.type) {
      case AnnotationType.text:
        return 'Text';
      case AnnotationType.image:
        return 'Image';
      case AnnotationType.audio:
        return 'Audio';
    }
  }

  String _getContentHint() {
    switch (widget.type) {
      case AnnotationType.text:
        return 'Enter the text to be annotated';
      case AnnotationType.image:
        return 'Enter image URL or description';
      case AnnotationType.audio:
        return 'Enter audio URL or description';
    }
  }

  @override
  Widget build(BuildContext context) {
    return BlocConsumer<AnnotationBloc, AnnotationState>(
      listener: (context, state) {
        if (state is AnnotationCreated) {
          ScaffoldMessenger.of(context).showSnackBar(
            const SnackBar(
              content: Text('Annotation created successfully!'),
              backgroundColor: AppColors.secondaryGreen500,
            ),
          );
          context.pop(state.annotation);
        } else if (state is AnnotationError) {
          ScaffoldMessenger.of(context).showSnackBar(
            SnackBar(
              content: Text(state.message),
              backgroundColor: AppColors.error,
            ),
          );
        }
      },
      builder: (context, state) {
        final isLoading = state is AnnotationLoading;

        return Scaffold(
          backgroundColor: AppColors.surface,
          body: SafeArea(
            child: Column(
              children: [
                // Modern Gradient Header
                Container(
                  width: double.infinity,
                  padding: const EdgeInsets.all(20),
                  decoration: BoxDecoration(
                    gradient: LinearGradient(
                      colors: [_getTypeColor(), _getTypeColor().withValues(alpha: 0.8)],
                      begin: Alignment.topLeft,
                      end: Alignment.bottomRight,
                    ),
                    borderRadius: const BorderRadius.only(
                      bottomLeft: Radius.circular(24),
                      bottomRight: Radius.circular(24),
                    ),
                  ),
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Row(
                        children: [
                          IconButton(
                            onPressed: () => context.pop(),
                            icon: const Icon(
                              Icons.arrow_back,
                              color: AppColors.onPrimary,
                            ),
                          ),
                          const SizedBox(width: 8),
                          Icon(
                            _getTypeIcon(),
                            color: AppColors.onPrimary,
                            size: 28,
                          ),
                          const SizedBox(width: 12),
                          Expanded(
                            child: Text(
                              'Create ${_getTypeLabel()} Annotation',
                              style: AppFonts.headlineMedium.copyWith(
                                color: AppColors.onPrimary,
                                fontWeight: FontWeight.bold,
                              ),
                            ),
                          ),
                        ],
                      ),
                      const SizedBox(height: 8),
                      Text(
                        'Create a new annotation task for your project',
                        style: AppFonts.bodyMedium.copyWith(
                          color: AppColors.onPrimary.withValues(alpha: 0.9),
                        ),
                      ),
                    ],
                  ),
                ),

                // Form Content
                Expanded(
                  child: SingleChildScrollView(
                    padding: const EdgeInsets.all(20),
                    child: Form(
                      key: _formKey,
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          // Content Field
                          Text(
                            'Content',
                            style: AppFonts.titleMedium.copyWith(
                              fontWeight: FontWeight.bold,
                              color: AppColors.onBackground,
                            ),
                          ),
                          const SizedBox(height: 8),
                          TextFormField(
                            controller: _contentController,
                            maxLines: widget.type == AnnotationType.text ? 6 : 3,
                            style: AppFonts.bodyMedium.copyWith(
                              color: AppColors.onBackground,
                            ),
                            decoration: InputDecoration(
                              hintText: _getContentHint(),
                              hintStyle: AppFonts.bodyMedium.copyWith(
                                color: AppColors.onSurfaceVariant,
                              ),
                              filled: true,
                              fillColor: AppColors.background,
                              prefixIcon: Padding(
                                padding: const EdgeInsets.only(bottom: 60),
                                child: Icon(
                                  _getTypeIcon(),
                                  color: _getTypeColor(),
                                ),
                              ),
                              border: OutlineInputBorder(
                                borderRadius: BorderRadius.circular(12),
                                borderSide: BorderSide.none,
                              ),
                              enabledBorder: OutlineInputBorder(
                                borderRadius: BorderRadius.circular(12),
                                borderSide: BorderSide(
                                  color: AppColors.neutralSlate600_30,
                                ),
                              ),
                              focusedBorder: OutlineInputBorder(
                                borderRadius: BorderRadius.circular(12),
                                borderSide: BorderSide(
                                  color: _getTypeColor(),
                                  width: 2,
                                ),
                              ),
                            ),
                            validator: (value) {
                              if (value == null || value.isEmpty) {
                                return 'Please enter content';
                              }
                              return null;
                            },
                          ),
                          const SizedBox(height: 24),

                          // Instructions Field
                          Text(
                            'Instructions (Optional)',
                            style: AppFonts.titleMedium.copyWith(
                              fontWeight: FontWeight.bold,
                              color: AppColors.onBackground,
                            ),
                          ),
                          const SizedBox(height: 8),
                          TextFormField(
                            controller: _instructionsController,
                            maxLines: 3,
                            style: AppFonts.bodyMedium.copyWith(
                              color: AppColors.onBackground,
                            ),
                            decoration: InputDecoration(
                              hintText: 'Provide instructions for annotators...',
                              hintStyle: AppFonts.bodyMedium.copyWith(
                                color: AppColors.onSurfaceVariant,
                              ),
                              filled: true,
                              fillColor: AppColors.background,
                              prefixIcon: const Padding(
                                padding: EdgeInsets.only(bottom: 40),
                                child: Icon(
                                  Icons.info_outline,
                                  color: AppColors.primaryIndigo600,
                                ),
                              ),
                              border: OutlineInputBorder(
                                borderRadius: BorderRadius.circular(12),
                                borderSide: BorderSide.none,
                              ),
                              enabledBorder: OutlineInputBorder(
                                borderRadius: BorderRadius.circular(12),
                                borderSide: BorderSide(
                                  color: AppColors.neutralSlate600_30,
                                ),
                              ),
                              focusedBorder: OutlineInputBorder(
                                borderRadius: BorderRadius.circular(12),
                                borderSide: const BorderSide(
                                  color: AppColors.primaryIndigo600,
                                  width: 2,
                                ),
                              ),
                            ),
                          ),
                          const SizedBox(height: 24),

                          // Labels
                          Text(
                            'Labels',
                            style: AppFonts.titleMedium.copyWith(
                              fontWeight: FontWeight.bold,
                              color: AppColors.onBackground,
                            ),
                          ),
                          const SizedBox(height: 4),
                          Text(
                            'Add labels that annotators can choose from',
                            style: AppFonts.bodySmall.copyWith(
                              color: AppColors.onSurfaceVariant,
                            ),
                          ),
                          const SizedBox(height: 8),
                          Row(
                            children: [
                              Expanded(
                                child: TextField(
                                  controller: _labelController,
                                  style: AppFonts.bodyMedium.copyWith(
                                    color: AppColors.onBackground,
                                  ),
                                  decoration: InputDecoration(
                                    hintText: 'Add label (e.g., Positive, Negative)',
                                    hintStyle: AppFonts.bodyMedium.copyWith(
                                      color: AppColors.onSurfaceVariant,
                                    ),
                                    filled: true,
                                    fillColor: AppColors.background,
                                    prefixIcon: Icon(
                                      Icons.label,
                                      color: _getTypeColor(),
                                    ),
                                    border: OutlineInputBorder(
                                      borderRadius: BorderRadius.circular(12),
                                      borderSide: BorderSide.none,
                                    ),
                                    enabledBorder: OutlineInputBorder(
                                      borderRadius: BorderRadius.circular(12),
                                      borderSide: BorderSide(
                                        color: AppColors.neutralSlate600_30,
                                      ),
                                    ),
                                    focusedBorder: OutlineInputBorder(
                                      borderRadius: BorderRadius.circular(12),
                                      borderSide: BorderSide(
                                        color: _getTypeColor(),
                                        width: 2,
                                      ),
                                    ),
                                  ),
                                  onSubmitted: (_) => _addLabel(),
                                ),
                              ),
                              const SizedBox(width: 8),
                              Container(
                                decoration: BoxDecoration(
                                  color: _getTypeColor(),
                                  borderRadius: BorderRadius.circular(12),
                                ),
                                child: IconButton(
                                  onPressed: _addLabel,
                                  icon: const Icon(Icons.add),
                                  color: AppColors.onPrimary,
                                ),
                              ),
                            ],
                          ),
                          if (_labels.isNotEmpty) ...[
                            const SizedBox(height: 16),
                            Wrap(
                              spacing: 8,
                              runSpacing: 8,
                              children: _labels.map((label) {
                                return Chip(
                                  label: Text(
                                    label,
                                    style: AppFonts.bodySmall.copyWith(
                                      color: _getTypeColor(),
                                    ),
                                  ),
                                  backgroundColor: _getTypeColor().withValues(alpha: 0.1),
                                  deleteIconColor: _getTypeColor(),
                                  onDeleted: () => _removeLabel(label),
                                  deleteIcon: const Icon(Icons.close, size: 18),
                                  side: BorderSide(
                                    color: _getTypeColor().withValues(alpha: 0.3),
                                  ),
                                );
                              }).toList(),
                            ),
                          ],
                          const SizedBox(height: 24),

                          // XP Reward
                          Text(
                            'XP Reward',
                            style: AppFonts.titleMedium.copyWith(
                              fontWeight: FontWeight.bold,
                              color: AppColors.onBackground,
                            ),
                          ),
                          const SizedBox(height: 8),
                          Container(
                            padding: const EdgeInsets.all(16),
                            decoration: BoxDecoration(
                              color: AppColors.background,
                              borderRadius: BorderRadius.circular(12),
                              border: Border.all(
                                color: AppColors.neutralSlate600_30,
                              ),
                            ),
                            child: Column(
                              children: [
                                Row(
                                  mainAxisAlignment: MainAxisAlignment.spaceBetween,
                                  children: [
                                    Text(
                                      'XP Value',
                                      style: AppFonts.bodyMedium.copyWith(
                                        color: AppColors.onSurfaceVariant,
                                      ),
                                    ),
                                    Container(
                                      padding: const EdgeInsets.symmetric(
                                        horizontal: 12,
                                        vertical: 6,
                                      ),
                                      decoration: BoxDecoration(
                                        color: AppColors.secondaryAmber500.withValues(alpha: 0.1),
                                        borderRadius: BorderRadius.circular(8),
                                      ),
                                      child: Row(
                                        children: [
                                          const Icon(
                                            Icons.star,
                                            size: 16,
                                            color: AppColors.secondaryAmber500,
                                          ),
                                          const SizedBox(width: 4),
                                          Text(
                                            '$_xpReward XP',
                                            style: AppFonts.titleSmall.copyWith(
                                              color: AppColors.secondaryAmber500,
                                              fontWeight: FontWeight.bold,
                                            ),
                                          ),
                                        ],
                                      ),
                                    ),
                                  ],
                                ),
                                Slider(
                                  value: _xpReward.toDouble(),
                                  min: 5,
                                  max: 50,
                                  divisions: 9,
                                  label: '$_xpReward XP',
                                  activeColor: _getTypeColor(),
                                  onChanged: (value) {
                                    setState(() {
                                      _xpReward = value.toInt();
                                    });
                                  },
                                ),
                              ],
                            ),
                          ),
                          const SizedBox(height: 32),

                          // Create Button
                          SizedBox(
                            width: double.infinity,
                            child: ElevatedButton(
                              onPressed: isLoading ? null : _createAnnotation,
                              style: ElevatedButton.styleFrom(
                                backgroundColor: _getTypeColor(),
                                padding: const EdgeInsets.symmetric(vertical: 16),
                                shape: RoundedRectangleBorder(
                                  borderRadius: BorderRadius.circular(12),
                                ),
                                elevation: 2,
                              ),
                              child: isLoading
                                  ? const SizedBox(
                                      height: 20,
                                      width: 20,
                                      child: CircularProgressIndicator(
                                        color: AppColors.onPrimary,
                                        strokeWidth: 2,
                                      ),
                                    )
                                  : Row(
                                      mainAxisAlignment: MainAxisAlignment.center,
                                      children: [
                                        const Icon(
                                          Icons.check_circle,
                                          color: AppColors.onPrimary,
                                        ),
                                        const SizedBox(width: 8),
                                        Text(
                                          'Create Annotation',
                                          style: AppFonts.buttonText.copyWith(
                                            color: AppColors.onPrimary,
                                            fontWeight: FontWeight.bold,
                                          ),
                                        ),
                                      ],
                                    ),
                            ),
                          ),
                          const SizedBox(height: 20),
                        ],
                      ),
                    ),
                  ),
                ),
              ],
            ),
          ),
        );
      },
    );
  }
}
